workflows:
  android-debug:
    name: NexTune X Debug Build

    environment:
      java: 17

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Set permissions
        script: chmod +x gradlew

      - name: Check Gradle version
        script: ./gradlew --version

      - name: Clean project
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
